version: '3'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - redis
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - REDIS_URL=redis://redis:6379/0  # recommended for clarity

  redis:
    image: redis:alpine

  celery:
    build: .
    command: celery -A app.core.config.celery_app worker --loglevel=info
    depends_on:
      - redis
    volumes:
      - .:/app
    working_dir: /app
    env_file: .env
    environment:
      - REDIS_URL=redis://redis:6379/0  # recommended for clarity